"""mark_as_done field

Revision ID: d16f412bc059
Revises: 984bd7983783
Create Date: 2023-07-04 20:04:23.096820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16f412bc059'
down_revision = '984bd7983783'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('mark_as_done', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'mark_as_done')
    # ### end Alembic commands ###
